const COMMENTS_PER_LOAD = 5;
const NUMBER_TAGS = 5;
const TEXTAREA_SYMBOLS = 140;
const ALERT_SHOW_TIME = 5000;
const RANDOM_PICTURES_COUNT = 10;
const FILE_TYPES = ['jpg', 'jpeg', 'png', 'gif'];

export {
  COMMENTS_PER_LOAD,
  NUMBER_TAGS,
  TEXTAREA_SYMBOLS,
  ALERT_SHOW_TIME,
  RANDOM_PICTURES_COUNT,
  FILE_TYPES
};
