const PICTURES_COUNT = 25;
const AVATAR_COUNT = 6;
const LIKE_MIN_COUNT = 15;
const LIKE_MAX_COUNT = 200;
const COMMENT_COUNT = 20;
const COMMENTS_PER_LOAD = 5;
const NUMBER_TAGS = 5;
const TEXTAREA_SYMBOLS = 140;
const DEFAULT_SCALE = 100;
const SCALE_STEP = 25;
const SCALE_MIN = 25;
const SCALE_MAX = 100;

export { PICTURES_COUNT, AVATAR_COUNT, LIKE_MIN_COUNT,
  LIKE_MAX_COUNT, COMMENT_COUNT, COMMENTS_PER_LOAD,
  NUMBER_TAGS, TEXTAREA_SYMBOLS, DEFAULT_SCALE,
  SCALE_STEP, SCALE_MIN, SCALE_MAX };
